version: '3.8'

services:
  db:
    image: postgres:15
    container_name: demo_postgres
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo_net

volumes:
  postgres_data:

networks:
  demo_net: