version: '3.8'

services:
  db:
    image: postgres:15
    container_name: demo_postgres
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo_net

  user-service:
    build: ../qa-demo-project/user-service
    container_name: demo_user_service
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - demo_net

  user-auth-service:
    build: ../qa-demo-project/user-auth-service
    container_name: demo_auth_service
    ports:
      - "8082:8080"
    depends_on:
          - db
    networks:
      - demo_net

  frontend:
    image: nginx:alpine
    container_name: demo_frontend
    volumes:
      - ../qa-demo-project/frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - demo_net

volumes:
  postgres_data:

networks:
  demo_net: