name: CI - Run Tests on PR

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker compose version

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Assemble Gradle JARs without tests
        run: ./gradlew :user-service:assemble :user-auth-service:assemble -x test

      - name: Run Docker Compose stack with timeout
        run: |
          timeout 15m docker compose -f docker-compose.yml up --build --abort-on-container-exit

      - name: Show Allure container logs (optional)
        if: always()
        run: docker logs demo-allure-service || true

      - name: Upload Allure Report Artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-docker-results